### ISSUE TITLE
Any reason you didn't use {array}.shift()() instead of {array}.splice(0,1)[0]() ?

### ISSUE THREAD

**Issue by DarrenSem** [javascriptlove/ready#1]
https://github.com/javascriptlove/ready/blob/master/ready.js#LL8C4-L8C29
```ready.r.splice(0,1)[0]();```
@javascriptlove What is the difference between ^ that and this... (they **both** change the contents of the source array)
```ready.r.shift()();```

Any reason you didn't use the latter? Perhaps this was written so long ago that ".splice" was Standard Practice at the time?

```
	var run = function() {
		clearTimeout(ready.t);
		while (ready.r.length)
			ready.r.splice(0,1)[0](); // <<< CONTEXT
	}
```

**Comment by javascriptlove** [comment]
@DarrenSem good question. It was so long ago, that I don't remember exactly. But, my guess would be browser support based on this
<img width="1439" alt="Markup 2023-05-03 at 22 13 51" src="https://user-images.githubusercontent.com/1811732/236039316-1f64f1b8-7e34-44eb-a910-b98432c2f6fa.png">

**Comment by DarrenSem** [comment]
Ahh, yes, a decade ago = feels like a thousand years ago, when it comes to web standards support. 😬 I only checked MDN and saw both existed at same time, but I never thought to also check mobile web browsers dates.
Thanks for replying so fast -- keep on grinding!

**Comment by javascriptlove** [comment]
Thanks! I'm closing this issue then :)
